#!/bin/bash

RSYNC_VALUE="${value:-"rsync"}"
BUTTON="${button:-}"

rsync_today() {
	journalctl -u rsync -o short-iso --since "${since:-today}" --until "${until:-now}"
}

rsync_statuses() {
	rsync_today | awk '{if ($4 == "sent" && $5 > 0) print "finished"; else if ($4 == "connect") print "started"; else if ($5 == "error:" || $7 == "error:") print "error"}'
}

rsync_last_success() {
	journalctl -u rsync -b -o short-iso | awk '{if ($4 == "sent") print $1}' | tail -n 1
}

rsync_last_success_unix() {
	date -d $(rsync_last_success) +%s
}

rsync_aging_unix() {
	date -d "${aging:-"3 days ago"}" +%s
}

_RSYNC_STATUSES=$(rsync_statuses)
RSYNC_LAST_STATUS=$(echo "${_RSYNC_STATUSES}" | tail -n 1)
RSYNC_SECOND_LAST_STATUS=$(echo "${_RSYNC_STATUSES}" | tail -n 2 | head -n 1)
VPN_STATUS=$(nmcli connection show "${DEFAULT_VPN}" | awk '/GENERAL.STATE/ {print $2}')

control() {
    regolith-control-center network
}

ACTION_1=$(xrescat i3xrocks.action.network.left "control")
ACTION_2=$(xrescat i3xrocks.action.network.middle "true")
ACTION_3=$(xrescat i3xrocks.action.network.right "true")
case $BUTTON in
    1) eval $ACTION_1 ;;
    2) eval $ACTION_2 ;;
    3) eval $ACTION_3 ;;
esac

if [ "${RSYNC_LAST_STATUS}" == "error" ]; then
	if [ "${RSYNC_SECOND_LAST_STATUS}" == "finished" ]; then
		LABEL_ICON=${icon:-$(xrescat i3xrocks.label.rsync.warning ⥮)}
		VALUE_COLOR=${warn_color:-$(xrescat i3xrocks.warning orange)}
	else
		LABEL_ICON=${icon:-$(xrescat i3xrocks.label.rsync.error ⥮)}
		VALUE_COLOR=${error_color:-$(xrescat i3xrocks.error.color red)}
	fi
elif [ "${RSYNC_LAST_STATUS}" == "finished" ]; then
	LABEL_ICON=${icon:-$(xrescat i3xrocks.label.rsync.success ⥮)}
	VALUE_COLOR=${success_color:-$(xrescat i3xrocks.success green)}
elif [ "${RSYNC_LAST_STATUS}" == "started" ]; then
	LABEL_ICON=${icon:-$(xrescat i3xrocks.label.rsync.syncing ⥮)}
	VALUE_COLOR=${progress_color:-$(xrescat i3xrocks.value.color blue)}
elif [[ -n "$(rsync_last_success)" && $(rsync_last_success_unix) -lt $(rsync_aging_unix) ]]; then
	LABEL_ICON=${icon:-$(xrescat i3xrocks.label.rsync.outdated ⥮)}
	VALUE_COLOR=${critical_color:-$(xrescat i3xrocks.critical.color purple)}
else
	LABEL_ICON=${icon:-$(xrescat i3xrocks.label.rsync ⥮)}
	VALUE_COLOR=${color:-$(xrescat i3xrocks.value.color white)}
fi

LABEL_COLOR=${label_color:-$(xrescat i3xrocks.label.color white)}

echo "<span color=\"${LABEL_COLOR}\">${LABEL_ICON}</span> <span color=\"${VALUE_COLOR}\">${RSYNC_VALUE}</span>"
echo "<span color=\"${VALUE_COLOR}\">${LABEL_ICON}</span>" # short text
